[package]
name = "ro-bura/xclass"
description = "just class framework"

version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

authors = ["RO_BURa"]
license = "MIT"

include = ["src", "src/**", "bin", "bin/**", "LICENSE", "default.project.json", "place.project.json", "wally.toml", "selene.toml"]
exclude = ["**"]

[dependencies]